spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiangchengyu998/config-repo.git
          username:
          password:
          basedir: E:\muke\config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3310/eureka/
  instance:
    prefer-ip-address: true
    # ip_address: 47.105.169.153
    # instance-id: ${eureka.instance.hostname}:${server.port}
server:
  port: 9999