spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiangchengyu998/config-repo.git
          username:
          password:
          basedir: /root/muke/basedir
eureka:
  client:
    service-url:
      defaultZone: http://47.105.169.153:3310/eureka/
  instance:
#    prefer-ip-address: false
    ipAddress: http://47.105.169.153
